/**
 * User API
 * User API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ApiRs} from "./apiRs";

export interface AllAccountRes extends ApiRs {
  data?: Array<DataAccount>;
}
export interface AccountRes extends ApiRs {
  data?: DataAccount;
}
export interface DataAccount {
  token: string;
  name: string;
  email: string;
  email_verified_at: string;
  created_at: Date;
  updated_at: Date;
  role: DataAccount.RoleEnum;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace DataAccount {
  export type RoleEnum = 'ADMIN' | 'SALE';
  export const RoleEnum = {
    ADMIN: 'ADMIN' as RoleEnum,
    SALE: 'SALE' as RoleEnum
  };
}
