/**
 * Influencer API
 * Influencer API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Influencer {
    id?: number;
    name?: string;
    status: Influencer.StatusEnum;
    created_at?: Date;
    phone?: string;
    email: string;
    birthday?: Date;
    maritalStatus?: Influencer.MaritalStatusEnum;
    gender?: Influencer.GenderEnum;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace Influencer {
    export type MaritalStatusEnum = 'MARRIED' | 'SINGLE';
    export const MaritalStatusEnum = {
        MARRIED: 'MARRIED' as MaritalStatusEnum,
        SINGLE: 'SINGLE' as MaritalStatusEnum
    };
    export type StatusEnum = 'ACTIVE' | 'WAIT' | 'PENDING';
    export const StatusEnum = {
      ACTIVE: 'ACTIVE' as StatusEnum,
      WAIT: 'WAIT' as StatusEnum,
      PENDING: 'PENDING' as StatusEnum,
    };
    export type GenderEnum = 'MALE' | 'FEMALE' | 'OTHER';
    export const GenderEnum = {
        MALE: 'MALE' as GenderEnum,
        FEMALE: 'FEMALE' as GenderEnum,
        OTHER: 'OTHER' as GenderEnum
    };
}
