/**
 * User API
 * User API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ApiRs} from "./apiRs";

export interface LoginRes extends ApiRs{
  data?: DataLogin;
}
export interface DataLogin {
  token: string;
  name: string;
  email: string;
  id: number;
  role: LoginRes.RoleEnum;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace LoginRes {
  export type RoleEnum = 'ADMIN' | 'SALE';
  export const RoleEnum = {
    ADMIN: 'ADMIN' as RoleEnum,
    SALE: 'SALE' as RoleEnum
  };
}
