/**
 * User API
 * User API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User {
  id?: number;
  name?: string;
  email?: string;
  password?: string;
  role?: User.RoleEnum;
  created_at: Date;
  remember: boolean;
}
export namespace User {
  export type RoleEnum = 'ADMIN' | 'USER' | 'SALE';
  export const RoleEnum = {
    ADMIN: 'ADMIN' as RoleEnum,
    USER: 'USER' as RoleEnum,
    SALE: 'SALE' as RoleEnum
  };
}
