/**
 * User API
 * User API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {User} from "./user";

export interface UserReq {
  id?: number;
  name?: string;
  email?: string;
  password?: string;
  confirm_password?: string;
  role?: User.RoleEnum;
}
